import { useState } from 'react'
import { reviews } from '../data/catalog.js'
const money = value => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export default function Product({ product, favorite, onFavorite, onAdd, onBack, onSeller }) {
  const [imageIndex, setImageIndex] = useState(0)
  if (!product) return null
  const discount = Math.round((1 - product.price / product.oldPrice) * 100)
  const images = [product.image, `${product.image}&sat=-35`, `${product.image}&con=12`]

  return <main className="container product-page"><button className="breadcrumb" onClick={onBack}>Início / {product.category} / {product.name}</button><div className="product-layout"><section><div className="gallery"><img src={images[imageIndex]} alt={product.name} /></div><div className="thumbs">{images.map((image, index) => <button className={index === imageIndex ? 'active' : ''} key={image} onClick={() => setImageIndex(index)}><img src={image} alt="" /></button>)}</div></section><section className="details"><span className="badge">{product.badge}</span><h1>{product.name}</h1><div className="rating">★★★★★ <b>{product.rating}</b> ({product.reviews} avaliações)</div><div className="price-box"><b>{money(product.price)}</b><del>{money(product.oldPrice)}</del><mark>-{discount}%</mark><p>ou 12x de {money(product.price / 12)} sem juros</p></div><div className="actions"><button className="primary" onClick={() => onAdd(product, true)}>🛒 Comprar agora</button><button className={favorite ? 'wish active' : 'wish'} onClick={() => onFavorite(product.id)}>{favorite ? '♥' : '♡'}</button></div><div className="features"><span>✅ Produto original</span><span>📦 Entrega em 1–3 dias</span><span>🔄 Troca em 30 dias</span><span>💳 12x sem juros</span></div><button className="seller-box" onClick={onSeller}>🏪 <span><b>AutoPeças Premium SP</b><small>⭐ 4.9 · 2.3k vendas · Vendedor verificado ✅</small></span>›</button></section></div><section className="reviews"><h2>💬 Avaliações</h2><div className="review-summary"><div><b>{product.rating}</b><span>★★★★★</span><small>{product.reviews} avaliações</small></div><div className="bars">{[75,18,5,2,1].map((value, index) => <p key={index}>{5 - index}★ <i><em style={{ width: `${value}%` }} /></i> {value}%</p>)}</div></div>{reviews.map(review => <article className="review" key={review.name}><b>👤 {review.name}</b><small>{review.date} · Compra verificada ✅</small><span>{'★'.repeat(review.stars)}</span><p>{review.text}</p></article>)}</section></main>
}
