import { useState } from 'react'

const partners = [
  { name: 'Auto Peças Premium', mark: 'AP', text: 'Frete rápido e peças verificadas' },
  { name: 'Motor Brasil', mark: 'MB', text: 'Especialista em motor e freios' },
  { name: 'Elétrica Rápida', mark: 'ER', text: 'Linha elétrica com garantia' },
  { name: 'Auto Centro', mark: 'AC', text: 'Manutenção para nacionais' }
]

export default function PartnerCarousel({ products, onOpen, onSellers }) {
  const [tab, setTab] = useState('offers')
  const list = tab === 'offers' ? products.filter(p => p.badge || p.oldPrice).slice(0, 8) : partners
  return <section className="partner-carousel">
    <style>{`.partner-carousel{padding:28px 0 48px}.partner-carousel__top{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:16px}.partner-carousel small,.home-intro small,.search-page__hero small{color:#ff5a1f;font-weight:800;letter-spacing:.8px;font-size:10px}.partner-carousel h2,.home-intro h2,.search-page__hero h1{margin:5px 0;font:700 clamp(27px,4vw,39px) Oswald, sans-serif}.partner-tabs{display:flex;gap:7px}.partner-tabs button{border:1px solid #343843;border-radius:999px;background:#20232b;color:#a5aaba;padding:8px 11px;font-weight:700;font-size:12px}.partner-tabs button.active{background:#ff5a1f;color:white;border-color:#ff5a1f}.partner-rail{display:flex;gap:14px;overflow:auto;scroll-snap-type:x mandatory;padding:2px 1px 12px}.promo-card,.partner-card{flex:0 0 min(280px,78vw);scroll-snap-align:start;border:1px solid #343843;border-radius:15px;overflow:hidden;background:#1a1c21;color:#f6f7fb;text-align:left}.promo-card img{width:100%;height:148px;object-fit:cover;display:block}.promo-card div,.partner-card div{padding:14px}.promo-card small{color:#ff5a1f}.promo-card b,.partner-card b{display:block;margin:5px 0}.promo-card span,.partner-card p{color:#a5aaba;font-size:12px}.partner-card{min-height:180px;background:linear-gradient(135deg,#252833,#17191e)}.partner-mark{display:grid;place-items:center;width:43px;height:43px;border-radius:12px;background:#ff5a1f;color:#fff;font-weight:900}.partner-card button{margin:11px 14px 15px;border:0;background:transparent;color:#ff6a37;font-weight:800}.home-intro{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:32px 0 12px}.home-intro p,.search-page__hero p{max-width:620px;color:#a5aaba;line-height:1.6}.search-page{padding-top:38px}.search-page__hero{margin-bottom:24px}@media(max-width:700px){.home-intro{display:block;padding-top:24px}.home-intro .primary{margin-top:8px}.partner-carousel__top{align-items:flex-start;flex-direction:column}.partner-tabs{width:100%}.partner-tabs button{flex:1}.search-page{padding-top:24px}}`}</style>
    <div className="partner-carousel__top"><div><small>{tab === 'offers' ? 'DESTAQUES DA SEMANA' : 'LOJAS VERIFICADAS'}</small><h2>{tab === 'offers' ? 'Ofertas que valem a pena' : 'Compre de quem entende'}</h2></div><div className="partner-tabs"><button className={tab === 'offers' ? 'active' : ''} onClick={() => setTab('offers')}>Promoções</button><button className={tab === 'partners' ? 'active' : ''} onClick={() => setTab('partners')}>Parceiros</button></div></div>
    <div className="partner-rail">{tab === 'offers' ? list.map(product => <button className="promo-card" key={product.id} onClick={() => onOpen(product)}><img src={product.image} alt="" /><div><small>{product.badge || 'OFERTA'}</small><b>{product.name}</b><span>R$ {Number(product.price).toFixed(2).replace('.', ',')}</span></div></button>) : list.map(partner => <article className="partner-card" key={partner.name}><div><span className="partner-mark">{partner.mark}</span><b>{partner.name}</b><p>{partner.text}</p></div><button onClick={onSellers}>Ver loja →</button></article>)}</div>
  </section>
}